on: push
jobs:
  build:
    name: Build and generate output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential libosmpbf-dev cmake protobuf-compiler
      - name: Compile
        run: ./compile-all.sh
      - name: Get Oregon data
        run: |
          cd /tmp && wget http://developer.trimet.org/schedule/gtfs.zip && unzip gtfs.zip
          cd /tmp && wget http://download.geofabrik.de/north-america/us/oregon-latest.osm.pbf
      # - name: Run GetCSVData (geojson out)
      #   run: |
      #     mkdir -p /tmp/out
      #     ./getcsvdata isle-of-man-latest.osm.pbf stops.txt /tmp/out
      - name: Run GetCSVData (geojson out)
        run: |
          mkdir -p /tmp/out
          ./getcsvdata /tmp/oregon-latest.osm.pbf /tmp/stops.txt /tmp/out
      - name: Output Summary
        run: |
          ls -alth /tmp/out
          echo ">> Word/Line/Char counts:"
          wc /tmp/out/*
          echo ">> Head:"
          head /tmp/out/*
          echo ">> Tail:"
          tail /tmp/out/*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-output-files
          path: |
            /tmp/out/*
